### ISSUE TITLE
[BUG] TextDisplay with style buffer doesn't work

### ISSUE THREAD

**Issue by brmmm3** [MoAlyousef/fltk-rs#151]
When I add a style buffer with set_styly_table_entry to the TextDisplay then the application doesn't work. It often crashes immediately. When it doesn't immediately crash, then the text is not displayed as expected. See the example terminal-colored.rs  in my fork in the master branch:
https://github.com/brmmm3/fltk-rs/blob/master/examples/terminal-colored.rs

**Comment by MoAlyousef** [comment]
Thanks for the typo fixes. I've merged the fixes.

Regarding set_style_table_entry, I'm able to reproduce the issue. It's because of a use-after-free in the C++ side. I'll try to fix it in a few hours. Then push a new version with the fixes this evening.

**Comment by MoAlyousef** [comment]
Hopefully it's fixed. I've also uploaded a similar example to yours:
https://github.com/MoAlyousef/fltk-rs/blob/master/examples/terminal_colored.rs

Notice that it uses the SimpleTerminal struct instead of TextDisplay. The advantage is that it has its own internal buffer so no need for a buffer in the constructor. However it still needs a style buffer. Another advantage is that it doesn't need the extra styling that TextDisplay needs, nor the cursor movement after appending since it does it automatically.
