### ISSUE TITLE
FileDialog's bad usage of strings

### ISSUE THREAD

**Issue by phase** [MoAlyousef/fltk-rs#16]
Hello! I just wanted to thank you for working on these bindings! I've been looking around for a simple GUI library for prototyping and this hit the spot!

There are a few issues I noticed when using the FileDialog:

```rust
let mut image_dialog = FileDialog::new(FileDialogType::BrowseFile);
image_dialog.set_filter("*.png");
image_dialog.show();
```
This example adds a filter, but instead of adding `*.png`, it contains a bunch of garbage after it. For me, it displayed an error message from a different crate (which you can imagine was difficult to debug). Changing the filter to `*.png\x00` works and shows that the `set_filter` method should append a null byte before passing it to FLTK.

Another issue I'm seeing is that there's no way to tell if a FileDialog succeeded or failed. If I close the file dialog without choosing a file, the program will segfault because `FileDialog::filename()` is trying to convert the empty string (or whatever FLTK is returning) to a UTF-8 String. Having these return `Option<String>` would be perfect.

I am using `fltk 0.1.13` on Fedora

**Comment by MoAlyousef** [comment]
Hello phase
Thank you for your kind words and for reporting this.
I tried it out and indeed it's because of the direct conversion from &str to const char*, I've fixed this now and bumped the version to 0.1.14. I've also fixed the segfault with filename(), however, it still returns a string, since the fltk version also returns a string. Adding an extra check on the user's side for Option or for an empty filename (using String::is_empty()) seems equivalent, but avoids the risk of crashing the gui because of a panic, which is important in gui programming and user experience. You can check the updated editor example for what I mean. But I would be interested to know your thoughts about this.

If you could try the updated version I would appreciate it :)

**Comment by phase** [comment]
I'd say returning an `Option<String>` is more ergonomic Rust but either way works. Everything involving file dialogs worked great!

I was messing around with the other dialog options and found another segfault. `message` & `alert` worked fine, but hitting _Cancel_ on the `input` dialog will segfault. Hitting _OK_ works fine, just the _Cancel_ button fails. Here's an example that crashes:

```rust
input("test", "test");
```

Thanks for your work!

**Comment by MoAlyousef** [comment]
Nice catch. I fixed this moments ago for input and password and updated again (0.1.15). However since FLTK returns NULL on cancellation, these return Option<String>.
Thanks again
