### ISSUE TITLE
Does fltk-rs support layout management (question and suggestion) ?

### ISSUE THREAD

**Issue by serge-hulne** [MoAlyousef/fltk-rs#190]
I think fltk originally had some layout management under C++.

Does fltk-rs support layout management?

If not, I would like to suggest it as an additional feature for fltk-rs.

**Comment by MoAlyousef** [comment]
Hi
Not that I’m aware of. I know that they have a gui builder called Fluid, maybe that allows creating layouts, I’m not really sure since I had never used it. The problem with Fluid is that it has it outputs C++ directly, which would be difficult to parse then translate into Rust. It also resuires embedding the callback code in C++ so that adds to the complexity unfortunately.

**Comment by serge-hulne** [comment]
Thank you very much for your answer, but I was referring to methods to pack widgets inside a container : https://www.fltk.org/doc-2.0/html/classfltk_1_1PackedGroup.html

**Comment by VladimirMarkelov** [comment]
It is from 2.0 docs. As far as I know 2.0 is kind of abandoned. So, I do not think it will be supported. As for current FLTK 1.x there is Fl_Pack: https://www.fltk.org/doc-1.3/classFl__Pack.html . And it is in this library sources:
https://github.com/MoAlyousef/fltk-rs/blob/35e1c61c43ac5ef32dd514695939db2116f29291/fltk-sys/src/table.rs#L518

**Comment by MoAlyousef** [comment]
I wasn’t aware of PackedGroup. It seems to have been part of the deprecated fltk 2.0. I’ll see how I can implement it on the Rust side since it’s missing from FLTK that’s used for this crate.

**Comment by serge-hulne** [comment]
Thank you very much indeed!
