### ISSUE TITLE
Why are some fltk examples commented out?

### ISSUE THREAD

**Issue by PonasKovas** [MoAlyousef/fltk-rs#369]
For example [tokio.rs](https://github.com/MoAlyousef/fltk-rs/blob/master/fltk/examples/tokio.rs) and [async_std.rs](https://github.com/MoAlyousef/fltk-rs/blob/master/fltk/examples/async_std.rs)

**Comment by MoAlyousef** [comment]
It’s just to avoid build failures when running `cargo build —examples` since these actually require tokio and async_std as dependencies, and I didn’t want to clutter the examples dir with several subprojects. There is a working example of using tokio in the fltk-rs-demos repo, along with other examples using other libraries.

**Comment by PonasKovas** [comment]
Why not just add `tokio` and `async_std` as dev-dependencies?

**Comment by MoAlyousef** [comment]
I commonly reclone the repo and run the examples on multiple local machines, virtual boxes and on CI. I can get a build running quite quickly by using the NUM_JOBS env variable for the cmake crate. I also test the bundled version to check there are no link errors related to libc or some Rust problems like with Msys2. So it makes things faster instead of having to wait for both tokio and async_std, it's also just a demonstration of how the code would look like, not something I would want to test. I'm more interested in build failures and visual layout issues, especially in regards to C strings, since fltk doesn't document what owns a char buffer and what doesn't. So I look for string corruption especially when implementing new widget methods which require strings.
