### ISSUE TITLE
Default values for color_chooser

### ISSUE THREAD

**Issue by alexxbb** [MoAlyousef/fltk-rs#445]
**Is your feature request related to a problem? Please describe.**

`dialog::color_chooser()` spawns a dialog for picking a color, but the default values are hardcoded in the function. This makes it impossible to set the default color into the color chooser widget.

**Describe the solution you'd like**

**Breaking API** - change the function signature

```rust
pub fn color_chooser(name: &str, cmode: i32, defaults: Option<(u8, u8, u8)) -> Option<(u8, u8, u8)>
```

**Non breaking** would be adding a new function name, something like 
```rust
 fn color_chooser_with_default(...)
```

**Comment by M4SSD35TRUCT10N** [comment]
I'm in favor of a second function name. Clear API and you ne knows exactly what this function will do.

**Comment by MoAlyousef** [comment]
Hi

I'm also in favor of the second option, something like: 
`fn color_chooser_with_default(name: &str, cmode: i32, col: (u8, u8, u8)) -> (u8, u8, u8)`
No Options. I can add it this evening.

As for the first function, `color_chooser`, we can change the defaults since it defauls to a black color without changing the api.
![image](https://user-images.githubusercontent.com/37966791/104742652-bed1e800-575b-11eb-8775-0fa430131c1c.png)

**Comment by alexxbb** [comment]
Sounds great! Thanks.
