### ISSUE TITLE
Request for version of app::awake() without parameters

### ISSUE THREAD

**Issue by dheijl** [MoAlyousef/fltk-rs#483]
**Is your feature request related to a problem? Please describe.**
After reading the fltk docs on awake_msg(), it is clear that messages can (and will be, at least on Windows) lost. Also, thread_msg() only returns the ***last*** message posted in the ring buffer, so memory leaks seem unavoidable in the current fltk-rs implementation.
The other "pending" awake_msg() calls are simply ignored/discarded by fltk as far as I can see. My tests on Windows seem to confirm that multiple queued awake_msg() calls do not cause multiple wait() wake-ups.   

**Describe the solution you'd like**
So I would propose to also implement a parameterless version of the awake() call, as it is a recommended practice in the fltk docs to update the GUI.

**Describe alternatives you've considered**
For now I just ignore any possible memory leaks caused by the boxing of the messages (I did not test the the behaviour of the callback version of awake() in this context).

**Additional context**

**Comment by MoAlyousef** [comment]
Hmm I had to check the docs. I had already created a wrapper for fl::awake() but never exposed it in the high level bindings. I'll release a new version 0.14.0 tonight, since I'll rename the app::awake(cb: FnMut()) to app::awake_callback, and the parameterless and the new app::awake will be parameterless. I also had several breaking changes to the App struct to make.

**Comment by dheijl** [comment]
Thanks! That's a lot of changes in 0.14.0.
I'll test the new awake() tomorrow.
