### ISSUE TITLE
global() for MenuExt

### ISSUE THREAD

**Issue by wyhinton** [MoAlyousef/fltk-rs#565]
Humbly requesting [global() ](https://www.fltk.org/doc-1.3/classFl__Menu__.html#aea0c7fce644de6b8703a6d8fff1941c0) function be added to MenuExt in the next update, unless I'm mistaken and it's already implemented with a different name. 

A couple of other miscellaneous functions for MenuItem/Window that might be useful:

MenuItem
- draw() for MenuItem (I know MenuItem does not impl WidgetExt, but I do see ```draw()``` in the FLTK [docs](https://www.fltk.org/doc-1.3/structFl__Menu__Item.html#a6f9672ace322a67dccf75c33f26c2a52))?
- measure() 
- image()
- text()

Window:
- shape()

**Comment by MoAlyousef** [comment]
Sure. I'll add them soon.

**Comment by MoAlyousef** [comment]
I've added them in master. 

A few notes:
- There's no text() method, however the label can be accessed via MenuItem::label() and set_label(). 
- MenuItem::set_image is marked unsafe since setting the label's text as well leads to an overwrite and UB. It appears to be internal to FLTK even though it's marked public. 
- MenuItem::draw() just draws the menu item itself at certain coordinates and size. It's not like WidgetBase::draw where draw functions can be used. It also appears to be internal to FLTK.
