### ISSUE TITLE
How to Not Get a MSDOS Console Window?

### ISSUE THREAD

**Issue by super119** [MoAlyousef/fltk-rs#70]
FLTK has described this:
https://www.fltk.org/doc-1.3/osissues.html#osissues_msdos_console
So it seems that for fltk-rs, we're missing something to get rid of the msdos console window? I think for the debug build, a msdos console window makes sense since we need it to check some debug outputs, but for the release build, we should get rid of it.

**Comment by MoAlyousef** [comment]
Hi
You need to add this in the beginning of your main.rs file:
#![windows_subsystem = "windows"]

**Comment by super119** [comment]
WOW, that works! Actually I tried to HACK the cmake files in fltk-sys and fltk yesterday but didn't make it. I'm surprised that this can be done in such a simple way! I did a grep "windows_subsystem" in fltk-rs source tree just now but didn't get a hit. Could you explain how it works? Besides, I think you should add this in the README. :)

**Comment by MoAlyousef** [comment]
So windows_subsystem is an attribute which signals the msvc linker to create a windows gui executable. It's like using ```int _tmain()``` and passing the ```-mwindows``` argument in a C++ executable, or if using cmake:  ``` add_executable(main WIN32 main.cpp) ```. 

However, it can't be used for libraries, that's why it's not used in fltk-rs. 

In Mac OS and Linux, rustc creates unix executables by default, but you can get a Mac OS bundle or a Linux AppImage using post-build tools, so no linker arguments there. 

I was thinking of adding a troubleshooting section or page in the README for such issues.

**Comment by super119** [comment]
So what you mean is that, the MSDOS console windows is caused by rustc while not fltk or fltk-rs? And this "#![windows_subsystem = "windows"]" is to tell rustc to create a windows GUI executable, right?

**Comment by MoAlyousef** [comment]
Yes. It can be useful for debugging, when you need to output to stderr for example during the execution of your app. It’s usually kept during the development process but removed for releases before deploying the app.

**Comment by MoAlyousef** [comment]
I've created a FAQ.md page with common questions/issues regarding builds, deployment etc. I'll close this issue now.
