### ISSUE TITLE
Crash when setting callback for button

### ISSUE THREAD

**Issue by brmmm3** [MoAlyousef/fltk-rs#77]
With the latest version 0.3.12 when I try to set a callback for the button:

        let mut ok = Button::default()
            .with_size(400, 40)
            .below_of(&frame, 0)
            .with_label("Ok");
        ok.set_callback(Box::new(move || std::process::exit(0)));

The program crashes with the following traceback:
 10: std::panicking::begin_panic<str*>
             at C:\Users\user\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:404
  11: fltk::button::{{impl}}::set_callback
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-0.3.12\src\button.rs:11
  12: fastcopy::MainWindow::run
             at .\src\main.rs:193

**Comment by MoAlyousef** [comment]
"thread 'main' panicked at 'Handling events requires that the window and widget be active!'"
It's a debug_assert and it's intentional.
Although most event would be handled normally, certain events require that both the window and the widget be able to take_events(). So as in the examples, event handling should be done after window::show().

**Comment by brmmm3** [comment]
Thanks. Ist's working now.
